Add EOSC Winter School 2024 news
galaxyproject/galaxy-hub pull request #2423
Opened 2024-02-27 15:20 UTC by itisAliRH

2024-02-27 16:22 UTC, bgruening commented
@erxleben

2024-02-27 17:02 UTC, erxleben requested changes

2024-02-27 17:02 UTC, erxleben commented on content/news/2024-02-27-eosc-winter-school-2024/index.md
> +To put into action this “hands-on, collaborative work” directly following the EOSC winter school a small informal hackathon was put in place. During this time multiple EOSC projects (Aquainfra, Euros
To put into action this “hands-on, collaborative work” directly following the EOSC winter school, a small informal hackathon was put in place. During this time multiple EOSC projects (AquaInfra, EuroScienceGateway, Fair-Ease, Raise, ...) worked together on Galaxy.

2024-02-28 11:08 UTC, bgruening approved these changes

2024-02-28 11:08 UTC, merged